## YAML Template.
---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mydemoapp
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to coding!
  management:
      endpoints:
          web:
              exposure:
                  include:"*"